#!/bin/bash
# ~/aws-update-instance-env.sh
# Updates AWS instance environment variables file

ENV_FILE="$HOME/.aws-instance-env"
TEMP_FILE="${ENV_FILE}.tmp"

# Function to get metadata using IMDSv2 (with IMDSv1 fallback)
aws_get_metadata() {
    local url="$1"
    local token=""

    token=$(curl -s -f --max-time 2 -X PUT "http://169.254.169.254/latest/api/token" \
        -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>/dev/null)

    if [ -n "$token" ]; then
        curl -s -f --max-time 2 -H "X-aws-ec2-metadata-token: $token" "$url" 2>/dev/null
    else
        curl -s -f --max-time 2 "$url" 2>/dev/null
    fi
}

# Setup user crontab if not already there
setup_cron() {
    # Check if cron job already exists
    if crontab -l 2>/dev/null | grep -q "update-aws-instance-vars.sh"; then
        return 0
    fi

    echo "Setting up daily cron job..."

    # Get existing crontab, add new job, install
    (crontab -l 2>/dev/null || echo ""; echo "# Update AWS instance environment variables daily at 2 AM"; echo "0 2 * * * $HOME/common/update-aws-instance-vars.sh >> $HOME/aws-instance-env.log 2>&1") | crontab -

    echo "Done: Added cron job to user crontab"
}

# Check if we're on EC2
if ! command -v curl >/dev/null 2>&1; then
    echo "Error: curl not installed" >&2
    exit 1
fi

# Get metadata
INSTANCE_ID=$(aws_get_metadata "http://169.254.169.254/latest/meta-data/instance-id" || echo "unknown")

if [ "$INSTANCE_ID" = "unknown" ]; then
    echo "Error: Not running on EC2 or metadata service unavailable" >&2
    exit 1
fi

REGION=$(aws_get_metadata "http://169.254.169.254/latest/meta-data/placement/region" || echo "unknown")
AVAILABILITY_ZONE=$(aws_get_metadata "http://169.254.169.254/latest/meta-data/placement/availability-zone" || echo "unknown")
PUBLIC_IP=$(aws_get_metadata "http://169.254.169.254/latest/meta-data/public-ipv4" || echo "N/A")
PRIVATE_IP=$(aws_get_metadata "http://169.254.169.254/latest/meta-data/local-ipv4" || echo "unknown")
INSTANCE_TYPE=$(aws_get_metadata "http://169.254.169.254/latest/meta-data/instance-type" || echo "unknown")

# Get instance name from tags (if AWS CLI is available)
if command -v aws >/dev/null 2>&1 && [ "$REGION" != "unknown" ]; then
    INSTANCE_NAME=$(aws ec2 describe-tags \
        --region "$REGION" \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=Name" \
        --query 'Tags[0].Value' \
        --output text 2>/dev/null)

    if [ -z "$INSTANCE_NAME" ] || [ "$INSTANCE_NAME" = "None" ]; then
        INSTANCE_NAME="$INSTANCE_ID"
    fi
else
    INSTANCE_NAME="$INSTANCE_ID"
fi

# Write to temp file
cat > "$TEMP_FILE" << EOF
# AWS EC2 Instance Environment Variables
# Auto-generated by ~/common/update-aws-instance-vars.sh
# Last updated: $(date)

export AWS_INSTANCE_ID="$INSTANCE_ID"
export AWS_INSTANCE_NAME="$INSTANCE_NAME"
export AWS_REGION="$REGION"
export AWS_AVAILABILITY_ZONE="$AVAILABILITY_ZONE"
export AWS_PUBLIC_IP="$PUBLIC_IP"
export AWS_PRIVATE_IP="$PRIVATE_IP"
export AWS_INSTANCE_TYPE="$INSTANCE_TYPE"
EOF

# Atomic move to prevent race conditions
mv "$TEMP_FILE" "$ENV_FILE"
chmod 644 "$ENV_FILE"

# Setup cron (will check if already exists)
setup_cron

echo "AWS instance environment updated: $INSTANCE_NAME ($INSTANCE_ID)"
